# Generated by Django 2.2.7 on 2019-11-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=30)),
                ('service_type', models.CharField(max_length=30)),
                ('services_supported', models.TextField()),
            ],
        ),
    ]
